{{- if .Values.createAzureOperatorSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: schema-operator-controller-settings
  namespace: {{.Release.Namespace}}
type: Opaque
data:
  AZURE_TENANT_ID: {{ .Values.azureTenantID | b64enc | quote }}
  AZURE_CLIENT_ID: {{ .Values.azureClientID | b64enc | quote }}
  {{- if .Values.azureClientSecret }}
  AZURE_CLIENT_SECRET: {{ .Values.azureClientSecret | b64enc | quote }}
  {{- end }}
  {{- if .Values.sqlpackageUser }}
  SCHEMAOP_SQLPACKAGE_USER: {{ .Values.sqlpackageUser | b64enc | quote }}
  SCHEMAOP_SQLPACKAGE_PASS: {{ .Values.sqlpackagePass | b64enc | quote }}
  {{- end }}
{{- end }}
