# permissions for end users to edit clusterexecuters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clusterexecuter-editor-role
rules:
  - apiGroups:
      - dbschema.microsoft.com
    resources:
      - clusterexecuters
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - dbschema.microsoft.com
    resources:
      - clusterexecuters/status
    verbs:
      - get
