# permissions for end users to view clusterexecuters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clusterexecuter-viewer-role
rules:
  - apiGroups:
      - dbschema.microsoft.com
    resources:
      - clusterexecuters
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - dbschema.microsoft.com
    resources:
      - clusterexecuters/status
    verbs:
      - get
