# permissions for end users to edit versioneddeplyments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: versioneddeplyment-editor-role
rules:
  - apiGroups:
      - dbschema.microsoft.com
    resources:
      - versioneddeplyments
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - dbschema.microsoft.com
    resources:
      - versioneddeplyments/status
    verbs:
      - get
