apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: schema-operator-proxy-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: schema-operator-proxy-role
subjects:
- kind: ServiceAccount
  name: schema-operator-controller-manager
  namespace: {{.Release.Namespace}}
