apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: schema-operator-leader-election-rolebinding
  namespace: {{.Release.Namespace}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: schema-operator-leader-election-role
subjects:
- kind: ServiceAccount
  name: schema-operator-controller-manager
  namespace: {{.Release.Namespace}}
